# Generated by Django 6.0.1 on 2026-02-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_display_name_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_hearts',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_hearts',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
