# Generated by Django 4.2.30 on 2026-05-22 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_last_login_face_captured_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginFaceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.BinaryField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_face_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_face_snapshots',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['user', '-captured_at'], name='login_face__user_id_eb67dc_idx')],
            },
        ),
    ]
