# Generated by Django 4.2.30 on 2026-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sync_superuser_role_to_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], help_text='Year level for students. Pick 1st-4th from the dropdown, or use "Other..." for non-standard programs (medical, PhD, etc.).', null=True),
        ),
    ]
