# Generated by Django 6.0.1 on 2026-01-31 05:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web-development', 'Web Development'), ('programming', 'Programming'), ('data', 'Data'), ('mobile', 'Mobile Development'), ('devops', 'DevOps'), ('other', 'Other')], default='programming', max_length=50)),
                ('language', models.CharField(help_text='Programming language (e.g., Python, JavaScript)', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('pdf_file', models.FileField(upload_to='learning_resources/pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='learning_resources/thumbnails/')),
                ('icon', models.CharField(default='📄', help_text='Emoji icon for the resource', max_length=10)),
                ('color_from', models.CharField(default='purple-500', help_text='Tailwind gradient start color', max_length=50)),
                ('color_to', models.CharField(default='purple-700', help_text='Tailwind gradient end color', max_length=50)),
                ('pages', models.PositiveIntegerField(default=1)),
                ('read_time', models.CharField(blank=True, help_text="Estimated read time (e.g., '2 hours')", max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_resources',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
