# Generated by Django 6.0.1 on 2026-02-01 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_learningresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('update', 'Platform Update'), ('feature', 'New Feature'), ('event', 'Event'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='update', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned announcements appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(default='CodeLogic', max_length=100)),
                ('site_tagline', models.CharField(default='Learn to Code, Level Up', max_length=200)),
                ('site_description', models.TextField(default='A gamified quiz platform that makes learning programming fun, engaging, and rewarding.', help_text='Meta description for SEO')),
                ('contact_email', models.EmailField(default='hello@codelogic.com', max_length=254)),
                ('max_hearts', models.PositiveIntegerField(default=10, help_text='Maximum hearts a user can have')),
                ('heart_regen_minutes', models.PositiveIntegerField(default=2, help_text='Minutes to regenerate 1 heart')),
                ('xp_per_correct_answer', models.PositiveIntegerField(default=10, help_text='XP earned per correct answer')),
                ('xp_perfect_bonus', models.PositiveIntegerField(default=50, help_text='Bonus XP for completing a quiz with 100%')),
                ('question_time_limit', models.PositiveIntegerField(default=30, help_text='Seconds per question')),
                ('questions_per_quiz_min', models.PositiveIntegerField(default=5, help_text='Minimum questions per quiz')),
                ('questions_per_quiz_max', models.PositiveIntegerField(default=10, help_text='Maximum questions per quiz')),
                ('pass_percentage', models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass a quiz')),
                ('xp_per_level', models.PositiveIntegerField(default=500, help_text='XP required per level (Level = 1 + XP // this value)')),
                ('max_topic_levels', models.PositiveIntegerField(default=15, help_text='Maximum levels per topic')),
                ('github_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('discord_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode (shows maintenance page)')),
                ('registration_enabled', models.BooleanField(default=True, help_text='Allow new user registrations')),
                ('email_verification_required', models.BooleanField(default=True, help_text='Require email verification for new accounts')),
                ('leaderboard_enabled', models.BooleanField(default=True, help_text='Show leaderboard to users')),
                ('learning_resources_enabled', models.BooleanField(default=True, help_text='Enable the Learn section with PDF resources')),
                ('announcement_text', models.TextField(blank=True, default='', help_text='Banner announcement shown to all users (leave blank to hide)')),
                ('announcement_type', models.CharField(choices=[('info', 'Info (Blue)'), ('success', 'Success (Green)'), ('warning', 'Warning (Yellow)'), ('error', 'Error (Red)')], default='info', max_length=20)),
                ('announcement_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
