# Generated by Django 6.0.1 on 2026-02-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_announcement_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningresource',
            name='color_from',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='color_to',
        ),
        migrations.RemoveField(
            model_name='learningresource',
            name='icon',
        ),
    ]
