# Generated by Django 6.0.1 on 2026-02-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_icon_and_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon key (e.g., react, python, javascript)', max_length=50),
        ),
    ]
