# Generated by Django 6.0.1 on 2026-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_topic_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload SVG, PNG, or any image for icon', null=True, upload_to='icons/categories/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='icon_file',
            field=models.ImageField(blank=True, help_text='Upload SVG, PNG, or any image for icon', null=True, upload_to='icons/topics/'),
        ),
    ]
