# Generated by Django 6.0.1 on 2026-02-02 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_add_icon_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Upload SVG, PNG, JPG, or other image for icon', null=True, upload_to='icons/categories/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico'])]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='icon_file',
            field=models.FileField(blank=True, help_text='Upload SVG, PNG, JPG, or other image for icon (falls back to category icon)', null=True, upload_to='icons/topics/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico'])]),
        ),
    ]
