# Generated by Django 6.0.1 on 2026-02-02 12:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_allow_svg_icons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Certificate title (defaults to topic name)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Custom description for the certificate')),
                ('icon_file', models.FileField(blank=True, help_text='Custom icon for certificate (defaults to topic icon)', null=True, upload_to='icons/certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='game.topic')),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['topic__category__order', 'topic__order'],
            },
        ),
        migrations.CreateModel(
            name='UserCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_stars', models.PositiveIntegerField(default=0)),
                ('total_xp_earned', models.PositiveIntegerField(default=0)),
                ('completion_date', models.DateTimeField(auto_now_add=True)),
                ('certificate_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='game.certificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_certificates',
                'ordering': ['-completion_date'],
                'unique_together': {('user', 'certificate')},
            },
        ),
    ]
