# Generated by Django 4.2.28 on 2026-02-23 06:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_add_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Main lesson text - keep it short and simple')),
                ('code_example', models.TextField(blank=True, help_text='Optional code example to show')),
                ('tip', models.TextField(blank=True, help_text='Optional quick tip or fun fact')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='game.topic')),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['topic', 'level', 'order'],
            },
        ),
    ]
