# Generated by Django 4.2.30 on 2026-04-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_useranswer_quizattempt_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='verification_captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='verification_photo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
