# Generated by Django 4.2.30 on 2026-05-09 11:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_quizattempt_verification_captured_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='auto_failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='auto_failed_reason',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='QuizSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('routine', 'Routine'), ('face_lost', 'Face Lost'), ('face_returned', 'Face Returned'), ('multiple_faces', 'Multiple Faces'), ('tab_hidden', 'Tab Hidden')], default='routine', max_length=20)),
                ('photo', models.BinaryField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='game.quizattempt')),
            ],
            options={
                'db_table': 'quiz_snapshots',
                'ordering': ['captured_at'],
                'indexes': [models.Index(fields=['attempt', 'captured_at'], name='quiz_snapsh_attempt_cc1a77_idx')],
            },
        ),
    ]
