# Generated by Django 4.2.30 on 2026-05-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_quizattempt_auto_failed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='auto_failed',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='auto_failed_reason',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='verification_captured_at',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='verification_photo',
        ),
        migrations.DeleteModel(
            name='QuizSnapshot',
        ),
    ]
