# Generated by Django 4.2.30 on 2026-05-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_quizattempt_auto_failed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list, help_text='Optional alternative accepted answers as a JSON list, e.g. ["5", "five"]. Used alongside correct_text_answer.'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_text_answer',
            field=models.TextField(blank=True, help_text='For "Fill in the Blank" and "What is the Output" - the canonical text the user must type.'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_text',
            field=models.TextField(blank=True, help_text='Raw typed answer for fill-blank / output questions.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='highlight_line',
            field=models.PositiveIntegerField(blank=True, help_text='For "Find the Error" - the 1-based line number containing the bug. This is also the correct answer the user must click.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.IntegerField(help_text='Integer answer: option index for multiple-choice, line number for find-error. -1 when the answer is text-based (see selected_text).'),
        ),
    ]
